# 신규 version 추가 시에 fReseved[5]는 f가 5개 필요하다는 것임을 명심하기!!

CYC_ColumnItem = {
    '4103' : 46,
    '4102' : 42,
    '4101' : 42,
    '4101_Gas' : 42,
    '4100' : 35,
    '4099' : 24,
    #'8196' : 우선 cts만
}

FORMAT = {
    '4099':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "f"             # fTemperature2;
    ), 
        
    '4100':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "fffffff"       # fReserved[5]; fRealDate;fRealClock;
    ), 
    
    '4101':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "fffffffff"     # fImpedance100ms, fImpedance1s, fImpedance5s, fImpedance30s, fImpedance60s, fAmbientTemp, fGasVoltage, fRealDate, fRealClock
    ), 
    '4101_Gas':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "ffffffffffffff"# fReserved[5]; fRealDate;fRealClock; fGasCO2; fGasTemp; fGasAH; fGasBaseline; fGasTVOC; fGasEthanol; fGasH2;
    ), 
    '4102':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "fffffffff"     # fImpedance100ms, fImpedance1s, fImpedance5s, fImpedance30s, fImpedance60s, fAmbientTemp, fGasVoltage, fRealDate, fRealClock
    )
    , 
        '4103':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "ffffffffffffff"     # fImpedance100ms, fImpedance1s, fImpedance5s, fImpedance30s, fImpedance60s, fAmbientTemp, fGasVoltage, fRealDate, fRealClock, fChamberTempSV, fChilerTempPV,fChilerTempSV, fChilerPumpPV, fChilerPumpSV
    )
    , 
    #     '4096': # ver 1
    # (
    #     "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
    #     "LLLLLL"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
    #     "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
    #     "L"             # ulGotoCycleNum
    #     "f"             # fIntegralCapacity;
    # )
    '4096': # ver 2
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "f"             # fIntegralCapacity;
        "f"             # fIntegralWattHour; # structure에서는 long인데 다른 버전에선 float라 float로 변경
        "IIIII"         # ulChargeCapacity, ulDischargeCapacity, ulChargeWattHour, ulDischargeWattHour, ulCVEndTime
        "fff"             # fReserved[3];
    ),
    
    #     '4096':
    # (
    #     "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
    #     "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
    #     "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
    #     "I"             # ulGotoCycleNum
    #     "f"             # fIntegralCapacity;
    #     "i"             # fIntegralWattHour;
    #     "IIIII"         # ulChargeCapacity, ulDischargeCapacity, ulChargeWattHour, ulDischargeWattHour, ulCVEndTime
    #     "fff"             # fReserved[3];
    # ),
    '8196':
    (
        "BBBBBBBB"      # chNo, chStepNo, chState, chStepType, chDataSelect, cReserved, chGradeCode, chMode
        "IIIIII"        # ulIndexFrom, ulIndexTo, ulCurrentCycleNum, ulTotalCycleNum, ulSaveSequence, ulReserved
        "ffffffffffff"  # fVoltage, fCurrent, fCapacity, fWatt, fWattHour, fStepTime, fTotalTime, fImpedance, fTemperature, fPressure, fAvgVoltage, fAvgCurrent
        "I"             # ulGotoCycleNum
        "ffffffff"      # fIntegralCapacity, fIntegralWattHour, fChargeCapacity, fDischargeCapacity, fChargeWattHour, fDischargeWattHour, fCVEndTime, fFarad
        "cc"            # totalTimeCarry, cReserved2
        "H"             # nCycleNum
        "fffff"         # fChambertemp, fChargeCCCapacity, fChargeCVCapacity, fDischargeCCCapacity, fDischargeCVCapacity
        "HH"            # wChCode, wReserved
        "ffffffffffffffffffffff"     # fImpedance100ms, fImpedance1s, fImpedance5s, fImpedance30s, fImpedance60s, fAmbientTemp, fGasVoltage, fRealDate, fRealClock, fChamberTempSV, fChilerTempPV,fChilerTempSV, fChilerPumpPV, fChilerPumpSV, fAuxPressure[4], fAuxThickness[4]
    )
}

RECORDBYTE = {'4100': 42,
            '4101':50, # 파일 구조에 2byte 만큼이 누락된건진 모르겠는데,,, 49임 원래는,,, 50으로 읽고 가니까 180byte로 딱 나누어 떨어짐!!
            '4101_Gas':42,
            '4102':50,
            '4103':50,
            '4096':40, # structure에는 39로 되어있음.
            '4099':42,
            '8196':58}

COLUMNS = {
    '4099':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved", # <- 원래 Code, Mode를 Code로 써서 바꿈
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "ulReserved",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "reserved;",
    "CycleNum",
    "Temperature2",
    ],
    '4100':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "ulReserved",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved2",
    "CycleNum",
    "Temperature2",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved",
    "Reserved[5]1",
    "Reserved[5]2",
    "Reserved[5]3",
    "Reserved[5]4",
    "Reserved[5]5",
    "RealDate",
    "RealClock",
],
    
    '4101':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "Reserved2",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved3",
    "CycleNum",
    "ChamberTemp",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved4",
    "Impedance100ms",
    "Impedance1s",
    "Impedance5s",
    "Impedance30s",
    "Impedance60s",
    "AmbientTemp",
    "GasVoltage",
    "RealDate",
    "RealClock"
],
    '4101_Gas':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "Reserved2",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved3",
    "CycleNum",
    "ChamberTemp",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved4",
    "Reserved[5]1",
    "Reserved[5]2",
    "Reserved[5]3",
    "Reserved[5]4",
    "Reserved[5]5",
    "RealDate",
    "RealClock",
    "GasCO2",
    "GasTemp",
    "GasAH",
    "GasBaseline",
    "GasTVOC",
    "GasEthanol",
    "GasH2",
],
    '4102':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "Reserved2",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved3",
    "CycleNum",
    "ChamberTemp",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved4",
    "Impedance100ms",
    "Impedance1s",
    "Impedance5s",
    "Impedance30s",
    "Impedance60s",
    "AmbientTemp",
    "GasVoltage",
    "RealDate",
    "RealClock"
], 
     '4103':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "Reserved2",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved3",
    "CycleNum",
    "ChamberTemp",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved4",
    "Impedance100ms",
    "Impedance1s",
    "Impedance5s",
    "Impedance30s",
    "Impedance60s",
    "AmbientTemp",
    "GasVoltage",
    "RealDate",
    "RealClock",
    "fChamberTempSV",
    "fChilerTempPV",
    "fChilerTempSV",
    "fChilerPumpPV",
    "fChilerPumpSV",
], 
    '4096':
     [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Mode", #원래 Code인데,,, 없어서 바꿔봄
    "GradeCode",
    "chReserved",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "lReserved",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Reserved[3]",
    "Reserved[3]1",
    "Reserved[3]2",
], 
     '8196':
    [
    "No",
    "StepNo",
    "State",
    "StepType",
    "DataSelect",
    "Reserved1",
    "GradeCode",
    "Mode",
    "IndexFrom",
    "IndexTo",
    "CurrentCycleNum",
    "TotalCycleNum",
    "SaveSequence",
    "Reserved2",
    "Voltage",
    "Current",
    "Capacity",
    "Watt",
    "WattHour",
    "StepTime",
    "TotalTime",
    "Impedance",
    "Temperature",
    "Pressure",
    "AvgVoltage",
    "AvgCurrent",
    "GotoCycleNum",
    "IntegralCapacity",
    "IntegralWattHour",
    "ChargeCapacity",
    "DischargeCapacity",
    "ChargeWattHour",
    "DischargeWattHour",
    "CVEndTime",
    "Farad",
    "TotalTimeCarry",
    "Reserved3",
    "CycleNum",
    "ChamberTemp",
    "ChargeCCCapacity",
    "ChargeCVCapacity",
    "DischargeCCCapacity",
    "DischargeCVCapacity",
    "ChCode",
    "Reserved4",
    "Impedance100ms",
    "Impedance1s",
    "Impedance5s",
    "Impedance30s",
    "Impedance60s",
    "AmbientTemp",
    "GasVoltage",
    "RealDate",
    "RealClock",
    "fChamberTempSV",
    "fChilerTempPV",
    "fChilerTempSV",
    "fChilerPumpPV",
    "fChilerPumpSV",
    'fAuxPressure[4]1',
    'fAuxPressure[4]2',
    'fAuxPressure[4]3',
    'fAuxPressure[4]4',
    'fAuxThickness[4]1',
    'fAuxThickness[4]2',
    'fAuxThickness[4]3',
    'fAuxThickness[4]4',
], 
     }


chCodeDict = {
    "1": "NonCell",
    "2": "System Error",
    "3": "Defective Cell",
    "4": "Cell Check Error",
    "64": "Time Complete",
    "65": "Voltage Complete",
    "66": "Current Complete",
    "67": "Capacity Complete",
    "68": "OCV Step Complete",
    "69": "Last Step Complete",
    "70": "Stopped by User",
    "71": "Pause",
    "72": "Check Step Complete",
    "73": "Ended for Next Step",
    "74": "Impedance Step Completed",
    "75": "ADV Step Completed",
    "76": "LOOP Step Completed",
    "77": "Delta Voltage Completed",
    "78": "SOC Completed",
    "79": "Temperature Completed",
    "80": "Process completed(Time)",
    "81": "Process completed(Voltage)",
    "82": "Process completed(Current)",
    "83": "Process completed(Capacity)",
    "84": "Process completed(Watt)",
    "85": "Process completed(WattHour)",
    "86": "Standby(Temper.)",
    "87": "Short Test Completed",
    "90": "Watt Complete",
    "91": "WattHour Complete",
    "92": "Accumulated Capacity Complete",
    "93": "Accumulated WattHour Complete",
    "94": "Cycle Time Complete",
    "95": "CV Time Complete",
    "96": "Inspection Overvoltage",
    "97": "Inspection Undervoltage",
    "98": "Inspection Upper Limit Voltage",
    "99": "Inspection Lower Limit Voltage",
    "100": "Inspection Upper Limit Current",
    "101": "Inspection Lower Limit Current",
    "102": "Contact Failure 1",
    "103": "Contact Failure 2",
    "104": "Contact Failure 3",
    "105": "BadCell1",
    "106": "BadCell2",
    "107": "BadCell3",
    "108": "Short",
    "109": "Location Error (None)",
    "110": "Location Error ()",
    "111": "Drop Voltage Error",
    "128": "Voltage Upper Limit",
    "129": "Voltage Lower Limit",
    "130": "LimitI Pause",
    "131": "LimitI End",
    "134": "OCV Upper Limit",
    "135": "OCV Lower Limit",
    "136": "Current Upper Limit",
    "137": "Current Lower Limit",
    "138": "LimitV Pause",
    "139": "LimitV End",
    "142": "Capacity Upper Limit",
    "143": "Capacity Lower Limit",
    "152": "User Completion",
    "153": "Pause Completion",
    "154": "Next Step Completion",
    "165": "Temperature Upper Limit",
    "166": "Temperature Lower Limit",
    "167": "Pattern Info. Read Error",
    "168": "JIG Sensor Error",
    "169": "Chamber Error",
    "170": "Inverter Error",
    "171": "Equipment Stop",
    "172": "=+Compare Line Error",
    "173": "=-Compare Line Error",
    "174": "Compare Line Ch. Error",
    "175": "Voltage Compare Upper Limit",
    "176": "Current Compare Upper Limit",
    "177": "Temper. Compare Excess",
    "178": "Meter Compare Upper Limit",
    "179": "Meter Compare Lower Limit",
    "180": "JIG Error",
    "181": "Cut of Temper. Line Wire",
    "182": "Network Connection Error",
    "183": "Short Tester Error",
    "184": "Short Tester Connection Error",
    "186": "Short Tester Singleness Mode",
    "208": "Voltage Error (Warning)",
    "209": "Current Error (Warning)",
    "210": "Circuit Overheat (Warning)",
    "211": "Control Power Error (SMPS)",
    "212": "Power Off(Switch)",
    "213": "UPS Power Error",
    "214": "UPS Battery Error",
    "215": "EMG (MAIN)",
    "216": "EMG (SUB)",
    "217": "Network Error",
    "220": "AUX Temper. Completed",
    "221": "AUX Temper. Upper Limit Complet",
    "222": "AUX Temper. Lower Limit Complet",
    "223": "AUX Volt. Completed",
    "224": "AUX Volt. Upper Limit Completed",
    "225": "AUX Volt. Lower Limit Completed",
    "226": "AUX Temper. Upper Limit",
    "227": "AUX Temper. Lower Limit",
    "228": "AUX Volt. Upper Limit",
    "229": "AUX Volt. Lower Limit",
    "230": "Temper. Excess Completed",
    "231": "DC Fan Error",
    "232": "Capa. Efficiency Complete",
    "233": "Capa. Efficiency Pause",
    "234": "Capa. Efficiency Cycle Complete",
    "235": "Cycle Capacity Complete",
    "236": "Power Efficiency Cycle Complete",
    "237": "Imp. Efficiency Cycle Complete",
    "238": "Power Efficiency Pause",
    "239": "Imp. Efficiency Pause",
    "240": "Cycle Voltage Complete",
    "241": "Cycle Voltage End",
    "242": "Door Open Detected",
    "243": "Smoke Detected",
    "244": "Delta Voltage Error",
    "245": "Delta Current Error",
    "246": "Delta Voltage Complete",
    "247": "Delta Current Complete",
    "248": "Capa. Efficiency Complete",
    "249": "Power Efficiency Complete",
    "250": "Imp. Efficiency Complete",
    "251": "Pause(Grade Check)",
    "252": "Complete(Grade Check)",
    "253": "Channel Error in Same Chamber",
    "260": "[PCU]Input Voltage Error",
    "261": "[PCU]Voltage Upper Limit",
    "262": "[PCU]Current Upper Limit",
    "263": "[PCU]Temperature Upper Limit",
    "264": "[PCU]PV Voltage Error",
    "265": "[PCU]Terminal Voltage Error",
    "266": "[PCU]Output Current Error",
    "268": "[PCU]Dischar. Vol. Source Error",
    "269": "[PCU]Output Curr. Balance Error",
    "270": "[PCU]External Relay Error",
    "271": "[PCU]output Contact Error",
    "273": "[PCU]Communication Error",
    "274": "[PCU]Unknown Error",
    "275": "[PCU]Work Mode Error",
    "276": "[PCU]LAN Connect Error",
    "277": "[PCU]Sequence No. Error",
    "280": "[INV]LAG SHORT CURR.",
    "281": "[INV]OVER CURRENT",
    "282": "[INV]OVER VOLTAGE",
    "283": "[INV]PRECHARGE FAIL",
    "284": "[INV]OVER CURRENT 2",
    "285": "[INV]CAN ERROR",
    "286": "[INV]OVER LOAD",
    "287": "[INV]OVER HEAT",
    "289": "[INV]LOW VOLTAGE",
    "291": "[INV]RESET 1",
    "292": "[INV]RESET 2",
    "293": "[INV]AC INPUT FAIL",
    "295": "[INV]HDC ERROR",
    "296": "[INV]STAND-BY",
    "310": "CV Fault Voltage Error",
    "311": "CV Fault Current Error",
    "315": "Diagnosis Pause",
    "316": "Diagnosis Complete",
    "318": "3rd Current Calculation Anomaly",
    "360": "TVOC Upper",
    "361": "TVOC Lower",
    "362": "eCO2 Upper",
    "363": "eCO2 Lower",
    "364": "TVOC Complete",
    "365": "eCO2 Complete",
    "400": "Sample Vent Detect",
    "401": "Sample Vent Detect",
    "402": "Rest Voltage Error",
    "403": "Chamber SV Error",
    "404": "Temp upper(EMG)",
    "405": "Sample Soft Vent Detect",
    "406": "Sample Hard Vent Detect",
    "412": "Voltage upper(MonPro)",
    "413": "Voltage upper(OVP)",
    "416": "Temp upper(MonPro)",
    "417": "Temp upper(OTP)",
    "418": "Voltage lower(MonPro)",
    "419": "Pause by group(OVP)",
    "420": "Pause by group(OTP)",
    "421": "Chamber DI Error",
    "422": "Chamber SV, Ambient Temp Deviation Error",
    "423": "Group Voltage Error",
    "424": "Group Time Error",
    "426": "Chamber Stop",
    "500": "COMServer Communication Error",
    "1128": "Voltage upper(Step)",
    "1129": "Voltage lower(Step)",
    "1134": "Voltage upper(Step)",
    "1135": "Voltage lower(Step)",
    "1136": "Current upper(Step)",
    "1137": "Current lower(Step)",
    "1142": "Capacity upper(Step)",
    "1143": "Capacity lower(Step)",
    "1165": "Temp upper(Step)",
    "1166": "Temp lower(Step)",
    "2134": "Voltage upper(Test)",
    "2135": "Voltage lower(Test)",
    "2128": "Voltage upper(Test)",
    "2129": "Voltage lower(Test)",
    "2136": "Current upper(Test)",
    "2137": "Current lower(Test)",
    "2142": "Capacity upper(Test)",
    "2143": "Capacity lower(Test)",
    "2165": "Temp upper(Test)",
    "2166": "Temp lower(Test)"
}